### ISSUE TITLE
Code Review points 

### ISSUE THREAD

**Issue by MahmoudMabrok** [Ahmed-P-Mostafa/ToDo-App#2]
- [adapters](https://github.com/Ahmed-P-Mostafa/ToDo-App/tree/master/app/src/main/java/com/polotika/todoapp/pojo/adapters) shouldbe moved to UI package 
 
 - [utlis](https://github.com/Ahmed-P-Mostafa/ToDo-App/tree/master/app/src/main/java/com/polotika/todoapp/pojo/utils) should be go to util package 
 
 - `pojo package` should be renamed to  `dataLayer` or `data`
 - `FCMNotifications.kt` should be go to something not current one

**Comment by Ahmed-P-Mostafa** [comment]
SOLVED

**Comment by Ahmed-P-Mostafa** [comment]
SOLVED
