### ISSUE TITLE
Constants names should be All UppperCase 

### ISSUE THREAD

**Issue by MahmoudMabrok** [Ahmed-P-Mostafa/ToDo-App#3]
https://github.com/Ahmed-P-Mostafa/ToDo-App/blob/3f56ff8fbdaea15ab50a84dca2be9017ac1b1d54/app/src/main/java/com/polotika/todoapp/pojo/utils/AppConstants.kt#L4-L12

**Comment by Ahmed-P-Mostafa** [comment]
SOLVED

**Comment by MahmoudMabrok** [comment]
Did you make PR for this solve? As I did not found fix for this point.

**Comment by Ahmed-P-Mostafa** [comment]
No I updated it and pushed it, you can check in the file now

**Comment by MahmoudMabrok** [comment]
it was my fault, i was opening link from message above so it was guide me to old commit. 

Good work.

**Comment by Ahmed-P-Mostafa** [comment]
many thanks for your guidance <3
